title: 元气萌动
description: 元气萌动品牌站点
url: "https://www.yuanqimoe.com"
baseurl: ""
markdown: kramdown
permalink: pretty
collections:
  products:
    output: true
    permalink: /products/:name/
defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product
